### PR TITLE
Migrate from go-bindata to Go-native embed

### PR DESCRIPTION
**Pull request by philippgille**
Hello :wave: , thanks for creating `trie` as an open source library! The WASM demo is particularly nice :+1: 

I noticed that despite using Go 1.18 it's not using the [native embedding functionality](https://pkg.go.dev/embed) that was [introduced in Go 1.16](https://go.dev/doc/go1.16#embed) and relied upon a 3rd party tool for the word list. This PR migrates that to the native Go embedding.

Tested locally with `make build-wasm` + `make server` and visiting localhost:8080 and typing some words to check if the behavior is like in the online demo.

Please don't hesitate to ask any questions you might have before merging.

### CODE REVIEW

**Comment by philippgille** [comment]
In the previous CI build a test failed, which I fixed.

The issue in the linter step might be a config issue in the GitHub Action:

```
   /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/use-go-embed*:refs/remotes/origin/use-go-embed* +refs/tags/use-go-embed*:refs/tags/use-go-embed*
  Error: The process '/usr/bin/git' failed with exit code 1
```

It sounds like it's looking for the branch in origin, but as origin it uses your original repo, not my fork with the feature branch, as per https://github.com/shivamMg/trie/actions/runs/3777250986/jobs/6427022314#step:4:39.

Could that be from this part: https://github.com/shivamMg/trie/blob/12ff642a9e1044164b8240a9e1fb4438f2dcd3dc/.github/workflows/ci.yml#L21-L22

Whereas most examples use the defaults from the `actions/checkout` workflow, like https://github.com/mvdan/github-actions-golang.

**Comment by shivamMg** [comment]
@philippgille I've fixed the CI. Could you try taking latest master pull in your branch?

**Comment by philippgille** [comment]
Ah great 👍

Would you prefer me to rebase on master or to merge master?

**Comment by shivamMg** [comment]
@philippgille You can merge master in your branch and then push. The CI which is failing in your PR should succeed after that push.

**Review by shivamMg — APPROVED** [review]

**Comment by shivamMg** [comment]
@philippgille Thank you for your contribution and detailed analysis of the CI failure. Have a happy new year!

**Comment by philippgille** [comment]
Thanks for the quick handling of the PR, happy new year to you too!

**Pull request merged**
